### ISSUE TITLE
MAKE file for compiling

### ISSUE THREAD

**Issue by karbassi** [omikun/ForceNap#21]
I see the `README.md` but the compile instructions could be easier.

Having a `MAKE` file would make it easier to follow. Or maybe a `BUILDING.md` or `COMPILING.md` file?

**Comment by karbassi** [comment]
@omikun can you provide instructions on how to compile the script with `rumps` and `py2app`?

**Comment by omikun** [comment]
added setup.py and instructions to run py2app to readme.
